### ISSUE TITLE
allow user-defined downloads directory

### ISSUE THREAD

**Issue by nick-youngblut** [Merck/deepbgc#18]
`deepbgc download` (version 0.1.10) downloads all files into the user's home directory. At our institute, our home directories are very limited in size, so requiring downloading of the deepbgc-assocaited files into the home directory can lead to some significant problems for us. It would help if `deepbgc download` allowed users to specify the download location.

**Comment by prihoda** [comment]
Hi @nick-youngblut. This is possible by setting the following env variable before running `deepbgc download` and any further `deepbgc` commands:
```
export DEEPBGC_DOWNLOADS_DIR="/path/to/download/dir"
```
The directory will be created if it does not exist.

This is not really mentioned in the documentation, I will fix that in the next release version, thanks!

**Comment by prihoda** [comment]
Docs improved https://github.com/Merck/deepbgc/releases/
Running `deepbgc download --help` will now print:
```
usage: deepbgc download [-h] [--debug]

    Download trained models and other file dependencies to the DeepBGC downloads directory.
    
    By default, files are downloaded to: '/Users/prihodad/Library/Application Support/deepbgc/data'
    Set DEEPBGC_DOWNLOADS_DIR env variable to specify a different downloads directory."
```

**Comment by nick-youngblut** [comment]
Thanks for the quick fix!
