### ISSUE TITLE
defaults in script docs

### ISSUE THREAD

**Issue by nick-youngblut** [Merck/deepbgc#19]
It would help to include the default values in the argparse `help`. Example: 

```
group.add_argument('-s', '--score', default=0.5, type=float,
                            help="Average protein-wise DeepBGC score threshold for extracting BGC regions from Pfam sequences (default: %(default)s).")
```

Otherwise, the user has to dig through your code to find the defaults.

**Comment by prihoda** [comment]
👍 Fixed in new version https://github.com/Merck/deepbgc/releases
