### ISSUE TITLE
allow for gzip genome fasta input

### ISSUE THREAD

**Issue by nick-youngblut** [Merck/deepbgc#23]
It would be nice if deepbgc allowed gzip'ed genome fasta input, which is allowed by Antismash v5. At least with deepbgc v0.1.13, the following error occurs if a gzip'ed fasta is provided as input:

```
ERROR   03/10 07:41:20   Please provide a GenBank or FASTA sequence with an appropriate file extension.
```

**Comment by prihoda** [comment]
Good idea, I added PR #24, it is now available from release https://github.com/Merck/deepbgc/releases/tag/v0.1.14
