### ISSUE TITLE
UserWarning: Reached maximum number of 50 sequences for plotting, some sequences will not be plotted.

### ISSUE THREAD

**Issue by thinkgenome** [Merck/deepbgc#27]
For this warning, while I am analysing metagenome contigs, can I change some deepbgc parameters to incorporate all the results in plot.

**Comment by prihoda** [comment]
Unfortunately this limit is hardcoded, if you want to see all the sequences in the plot, you can:
1) Split the input contig files into maximum 50 sequences per file and process them with DeepBGC separately
2) Plot the results yourself using the `score` column in the output `.pfam.tsv` file.

**Comment by thinkgenome** [comment]
Thanks @prihoda
