### ISSUE TITLE
TensorFlow version problem

### ISSUE THREAD

**Issue by ahmedmoustafa** [Merck/deepbgc#38]
New installations of deepbgc fail because of the installed new versions of TensorFlow:

```
root@a492456632b1:~# pip install deepbgc
Collecting deepbgc
  Using cached deepbgc-0.1.18-py3-none-any.whl (63 kB)
Collecting matplotlib<3.1,>=2.2.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
Collecting numpy<1.17,>=1.16.1
  Using cached numpy-1.16.6.zip (5.1 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0.0,>=1.12.0 (from deepbgc) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<2.0.0,>=1.12.0 (from deepbgc)
root@a492456632b1:~#
```

Here in the info for the installed TensorFlow:

```
root@a492456632b1:~# pip show tensorflow
Name: tensorflow
Version: 2.3.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/miniconda3/lib/python3.8/site-packages
Requires: wrapt, absl-py, keras-preprocessing, google-pasta, gast, grpcio, wheel, tensorboard, h5py, astunparse, opt-einsum, tensorflow-estimator, six, scipy, numpy, termcolor, protobuf
Required-by:
root@a492456632b1:~#
```
<img width="935" alt="screenshot" src="https://user-images.githubusercontent.com/958957/91588191-14962700-e958-11ea-88b5-5a93bf1281b3.png">

**Comment by prihoda** [comment]
Hi @ahmedmoustafa, thanks for the heads up! Are you able to install with Python 3.7? I recommend installing using conda, which can also download the supported Python version for you. 

Looks like on Python 3.8, only Tensorflow >= 2.2 is supported, and porting our code would currently be a big effort. I updated the README to reflect that.

**Comment by ahmedmoustafa** [comment]
Hi @prihoda I used to be able to install fine with Python 3.7 but no longer with 3.8. Thank you so much for the recommendation.
