### ISSUE TITLE
Test run not working

### ISSUE THREAD

**Issue by ariverosw** [Merck/deepbgc#39]
Hi I'm trying to implement this pipeline in my work, but I'm facing problems. The pipeline was conda installed according with instruction in you GitHub. Here's the error:

$ deepbgc --help
Traceback (most recent call last):
  File "/apps/deepbgc/0.1.18/bin/deepbgc", line 6, in <module>
    from deepbgc.main import main
  File "/apps/deepbgc/0.1.18/lib/python3.7/site-packages/deepbgc/__init__.py",
line 2, in <module>
    from .pipeline import DeepBGCClassifier, DeepBGCDetector,
HmmscanPfamRecordAnnotator, DeepBGCAnnotator, ProdigalProteinRecordAnnotator
  File
"/apps/deepbgc/0.1.18/lib/python3.7/site-packages/deepbgc/pipeline/__init__.py",
line 1, in <module>
    from .classifier import DeepBGCClassifier
  File
"/apps/deepbgc/0.1.18/lib/python3.7/site-packages/deepbgc/pipeline/classifier.py",
line 4, in <module>
    from deepbgc import util
  File "/apps/deepbgc/0.1.18/lib/python3.7/site-packages/deepbgc/util.py", line
18, in <module>
    from Bio.Alphabet import SingleLetterAlphabet, generic_dna
  File
"/apps/deepbgc/0.1.18/lib/python3.7/site-packages/Bio/Alphabet/__init__.py",
line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet
can simply be ignored and removed from scripts. In a few cases, you may need to
specify the ``molecule_type`` as an annotation on a SeqRecord for your script
to work correctly. Please see https://biopython.org/wiki/Alphabet for more
information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the
alphabet can simply be ignored and removed from scripts. In a few cases, you
may need to specify the ``molecule_type`` as an annotation on a SeqRecord for
your script to work correctly. Please see https://biopython.org/wiki/Alphabet
for more information.

Thanks in advance,

Alejandro

**Comment by prihoda** [comment]
Hi @ariverosw, good catch, looks like we need to require an older version of BioPython, please try to install `pip install biopython==1.76` into your environment and let me know if that fixed the issue.

**Comment by ariverosw** [comment]
Hi @prihoda. Thanks for the reply. I've corrected this issue, but now when running the following I'm getting several warnings.

```bash
deepbgc info
```
--------------------------------------------------------
 _____                  ____    ____   ____ 
 |  _ \  ___  ___ ____ | __ )  / ___) / ___)
 | | \ \/ _ \/ _ \  _ \|  _ \ | |  _ | |    
 | |_/ /  __/  __/ |_) | |_) || |_| || |___ 
 |____/ \___|\___| ___/|____/  \____| \____)
=================|_|===== version 0.1.18 =====
INFO    24/09 10:12:15   Using custom downloads dir: /blue/burne/share/arwalker/quick/deepbgc
INFO    24/09 10:12:15   Available data files: ['Pfam-A.31.0.hmm.h3p', 'Pfam-A.31.0.clans.tsv', 'Pfam-A.31.0.hmm.h3i', 'Pfam-A.31.0.hmm.h3f', 'Pfam-A.31.0.hmm', 'Pfam-A.31.0.hmm.h3m']
INFO    24/09 10:12:15   ================================================================================
INFO    24/09 10:12:15   Available detectors: ['clusterfinder_original', 'clusterfinder_retrained', 'clusterfinder_geneborder', 'deepbgc']
INFO    24/09 10:12:15   --------------------------------------------------------------------------------
INFO    24/09 10:12:15   Model: clusterfinder_original
INFO    24/09 10:12:15   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/detector/clusterfinder_original.pkl
WARNING 24/09 10:12:15   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    24/09 10:12:15   --------------------------------------------------------------------------------
INFO    24/09 10:12:15   Model: clusterfinder_retrained
INFO    24/09 10:12:15   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/detector/clusterfinder_retrained.pkl
WARNING 24/09 10:12:15   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    24/09 10:12:15   --------------------------------------------------------------------------------
INFO    24/09 10:12:15   Model: clusterfinder_geneborder
INFO    24/09 10:12:15   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/detector/clusterfinder_geneborder.pkl
WARNING 24/09 10:12:15   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    24/09 10:12:15   --------------------------------------------------------------------------------
INFO    24/09 10:12:15   Model: deepbgc
INFO    24/09 10:12:15   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/detector/deepbgc.pkl
Using TensorFlow backend.
WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 4
OMP: Info #156: KMP_AFFINITY: 1 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 1 packages x 1 cores/pkg x 1 threads/core (1 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 
OMP: Info #250: KMP_AFFINITY: pid 27260 tid 27260 thread 0 bound to OS proc set 4
WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING 24/09 10:12:21   From /apps/deepbgc/0.1.18/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

INFO    24/09 10:12:21   Type: KerasRNN
INFO    24/09 10:12:21   Version: 0.1.0
INFO    24/09 10:12:21   Timestamp: 1551305667.986168 (2019-02-27T17:14:27.986168)
INFO    24/09 10:12:21   ================================================================================
INFO    24/09 10:12:21   Available classifiers: ['product_activity', 'product_class']
INFO    24/09 10:12:21   --------------------------------------------------------------------------------
INFO    24/09 10:12:21   Model: product_activity
INFO    24/09 10:12:21   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/classifier/product_activity.pkl
/apps/deepbgc/0.1.18/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
/apps/deepbgc/0.1.18/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)
/apps/deepbgc/0.1.18/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.2 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/apps/deepbgc/0.1.18/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.2 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
INFO    24/09 10:12:22   Type: RandomForestClassifier
INFO    24/09 10:12:22   Version: 0.1.0
INFO    24/09 10:12:22   Timestamp: 1551781433.886473 (2019-03-05T05:23:53.886473)
INFO    24/09 10:12:22   --------------------------------------------------------------------------------
INFO    24/09 10:12:22   Model: product_class
INFO    24/09 10:12:22   Loading model from: /blue/burne/share/arwalker/quick/deepbgc/0.1.0/classifier/product_class.pkl
INFO    24/09 10:12:22   Type: RandomForestClassifier
INFO    24/09 10:12:22   Version: 0.1.0
INFO    24/09 10:12:22   Timestamp: 1551781410.019103 (2019-03-05T05:23:30.019103)
INFO    24/09 10:12:22   ================================================================================
WARNING 24/09 10:12:22   Some warnings detected, check the output above

**Comment by prihoda** [comment]
Yes these should be fine. You could also do `pip install tensorflow==1.12.0`, which should get rid of the warnings, but I think you should be all set. I will close this issue, please let us know if you encounter any more issues.
