### ISSUE TITLE
Is there other way to download data set?[speed restriction]

### ISSUE THREAD

**Issue by Bollie15** [Merck/deepbgc#41]
Hi, I always get some trouble as follow when I download data model by `deepbgc download`.
```shell
:~$ deepbgc download
 _____                  ____    ____   ____ 
 |  _ \  ___  ___ ____ | __ )  / ___) / ___)
 | | \ \/ _ \/ _ \  _ \|  _ \ | |  _ | |    
 | |_/ /  __/  __/ |_) | |_) || |_| || |___ 
 |____/ \___|\___| ___/|____/  \____| \____)
=================|_|===== version 0.1.10 =====
INFO    10/10 11:48:16   ================================================================================
INFO    10/10 11:48:16   Checking: /home/mima123456/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl
INFO    10/10 11:48:16   Downloading: https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl
ERROR   10/10 11:57:55   104
Traceback (most recent call last):
  File "/home/mima123456/miniconda3/lib/python3.8/site-packages/deepbgc/main.py", line 113, in main
    run(argv)
  File "/home/mima123456/miniconda3/lib/python3.8/site-packages/deepbgc/main.py", line 102, in run
    args.func.run(**args_dict)
  File "/home/mima123456/miniconda3/lib/python3.8/site-packages/deepbgc/command/download.py", line 20, in run
    util.download_files(DOWNLOADS)
  File "/home/mima123456/miniconda3/lib/python3.8/site-packages/deepbgc/util.py", line 393, in download_files
    download_file(url=url, target_path=target_path, checksum=checksum, gzipped=gzipped)
  File "/home/mima123456/miniconda3/lib/python3.8/site-packages/deepbgc/util.py", line 415, in download_file
    urlretrieve(url, download_path)
  File "/home/mima123456/miniconda3/lib/python3.8/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/home/mima123456/miniconda3/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/home/mima123456/miniconda3/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/home/mima123456/miniconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/mima123456/miniconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mima123456/miniconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
ERROR   10/10 11:57:55   ================================================================================
ERROR   10/10 11:57:55   DeepBGC failed with ConnectionResetError: 104
ERROR   10/10 11:57:55   ================================================================================
ERROR   10/10 11:57:55   Connection reset by peer
ERROR   10/10 11:57:55   ================================================================================
```

I don't know why I can't downlaod this data, and it seems that the speed of access to Github is restricted. So is there any other way to download data?

**Comment by prihoda** [comment]
Hi @Bollie15, you can download `https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl` yourself and put in this location: `/home/mima123456/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl`.

**Comment by Bollie15** [comment]
> Hi @Bollie15, you can download `https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl` yourself and put in this location: `/home/mima123456/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl`.

It' help for me. But I cannot download other file again. Can you tell me which files to download manually? Downloading in the terminal is not as fast as manually downloading in the browser.

**Comment by prihoda** [comment]
You can look for these lines:
```
INFO    10/10 11:48:16   Checking: /home/mima123456/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl
INFO    10/10 11:48:16   Downloading: https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl
```
The first line shows the expected location, the second line shows the URL to download

**Comment by Bollie15** [comment]
> You can look for these lines:
> 
> ```
> INFO    10/10 11:48:16   Checking: /home/mima123456/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl
> INFO    10/10 11:48:16   Downloading: https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl
> ```
> 
> The first line shows the expected location, the second line shows the URL to download

I'm sorry to reply you so late. I download all the required file from the URL, and download the  _Escherichia coli_ genome from NCBI. Then I follow the software tips to tap `deepbgc pipeline ./mySeq.fa`. Fortunately, I got some of the results. 

Thank you for developing such a powerful software.👍

**Comment by prihoda** [comment]
Hi @Bollie15, that's great news. The `pr.png` and `roc.png` files are only present during validation, so these are expected to be missing. I'm closing this issue, let me know if you encounter anything else.
