### ISSUE TITLE
MD5SUM is not match

### ISSUE THREAD

**Issue by qb-lyu** [Merck/deepbgc#42]
MD5 is not match with `md5_checksums` in line 67 and line 74 of script [data.py](https://github.com/Merck/deepbgc/blob/master/deepbgc/data.py)
data.py
```
{
        'url': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam{}/Pfam-A.hmm.gz'.format(PFAM_DB_VERSION),
        'target': PFAM_DB_FILE_NAME,
        'gzip': True,
        'after': util.run_hmmpress,
        'checksum': '79a3328e4c95b13949a4489b19959fc5',
        'versioned': False
    },
    {
        'url': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam{}/Pfam-A.clans.tsv.gz'.format(PFAM_DB_VERSION),
        'target': PFAM_CLANS_FILE_NAME,
        'gzip': True,
        'checksum': 'a0a4590ffb2b33b83ef2b28f6ead886b',
        'versioned': False
    }
```
md5_checksums of **Pfam31.0**: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam31.0/md5_checksums
```
8951c2a33e7f77c562473097d6ac2b33  Pfam-A.clans.tsv.gz
b6fda5fdc90d24fbc1484d3b641d4e32  Pfam-A.hmm.gz
```

**Comment by prihoda** [comment]
Hi @qb-lyu, thanks for the heads up! I updated the hashes, the changes are now in the master branch, the new Bioconda release should be ready by the end of the week.

**Comment by qb-lyu** [comment]
> Hi @qb-lyu, thanks for the heads up! I updated the hashes, the changes are now in the master branch, the new Bioconda release should be ready by the end of the week.

I AM SO SORRY, I checked carefully and found that the previous version was free of errors. The mismatch is due to the script checking the MD5 of the unzipped file rather than the gz file. I apologize for the unnecessary work I have caused you.

**Comment by prihoda** [comment]
Haha no problem, I should have checked more carefully, fixed the hashes back :) I implemented the hash a while ago, so I forgot we do the hash only after uncompressing
