### ISSUE TITLE
No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by aescasinas** [Merck/deepbgc#44]
EDIT:

I fixed the issue by downgrading scikit-learn to version 0.21 (`conda install scikit-learn=0.21`). sklearn.ensemble.forest is deprecated in version >= 0.22, where it uses sklearn.ensemble._forest

**Hi,**

**I created a conda environment and installed deepbgc. The command I used was:**

`conda create -n deepbgc deepbgc`

**I then ran** `deepbgc download` **followed by** `deepbgc info`. **I get a warning:**

INFO    20/01 14:38:43   Type: KerasRNN
INFO    20/01 14:38:43   Version: 0.1.0
INFO    20/01 14:38:43   Timestamp: 1551305667.986168 (2019-02-27T22:14:27.986168)
INFO    20/01 14:38:43   ================================================================================
INFO    20/01 14:38:43   Available classifiers: ['product_activity', 'product_class']
INFO    20/01 14:38:43   --------------------------------------------------------------------------------
INFO    20/01 14:38:43   Model: product_activity
INFO    20/01 14:38:43   Loading model from: /home/nick/.local/share/deepbgc/data/0.1.0/classifier/product_activity.pkl
WARNING 20/01 14:38:43   Model not supported: No module named 'sklearn.ensemble.forest'
INFO    20/01 14:38:43   --------------------------------------------------------------------------------
INFO    20/01 14:38:43   Model: product_class
INFO    20/01 14:38:43   Loading model from: /home/nick/.local/share/deepbgc/data/0.1.0/classifier/product_class.pkl
WARNING 20/01 14:38:43   Model not supported: No module named 'sklearn.ensemble.forest'
INFO    20/01 14:38:43   ================================================================================
WARNING 20/01 14:38:43   Some warnings detected, check the output above

**When I try the pipeline, I get an error:**

ERROR   20/01 14:43:59   ================================================================================
ERROR   20/01 14:43:59   DeepBGC failed with ModuleNotFoundError: No module named 'sklearn.ensemble.forest'
ERROR   20/01 14:43:59   ================================================================================

**The deepbgc package installed includes:**

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  absl-py            conda-forge/linux-64::absl-py-0.11.0-py37h89c1867_0
  appdirs            conda-forge/noarch::appdirs-1.4.4-pyh9f0ad1d_0
  astor              conda-forge/noarch::astor-0.8.1-pyh9f0ad1d_0
  biopython          conda-forge/linux-64::biopython-1.76-py37h516909a_0
  c-ares             conda-forge/linux-64::c-ares-1.17.1-h36c2ea0_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.12.5-ha878542_0
  cached-property    conda-forge/noarch::cached-property-1.5.1-py_0
  certifi            conda-forge/linux-64::certifi-2020.12.5-py37h89c1867_1
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  deepbgc            bioconda/noarch::deepbgc-0.1.21-py_0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  gast               conda-forge/noarch::gast-0.4.0-pyh9f0ad1d_0
  google-pasta       conda-forge/noarch::google-pasta-0.2.0-pyh8c360ce_0
  grpcio             conda-forge/linux-64::grpcio-1.34.1-py37hb27c1af_0
  h5py               conda-forge/linux-64::h5py-3.1.0-nompi_py37h1e651dc_100
  hdf5               conda-forge/linux-64::hdf5-1.10.6-nompi_h6a2412b_1114
  hmmer              bioconda/linux-64::hmmer-3.3.1-he1b5a44_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-3.4.0-py37h89c1867_0
  joblib             conda-forge/noarch::joblib-1.0.0-pyhd8ed1ab_0
  jpeg               conda-forge/linux-64::jpeg-9d-h36c2ea0_0
  keras              conda-forge/linux-64::keras-2.2.5-py37_1
  keras-applications conda-forge/noarch::keras-applications-1.0.8-py_1
  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.2-pyhd8ed1ab_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.3.1-py37h2527ec5_1
  krb5               conda-forge/linux-64::krb5-1.17.2-h926e7f8_0
  lcms2              conda-forge/linux-64::lcms2-2.11-hcbb858e_1
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_1
  libblas            conda-forge/linux-64::libblas-3.9.0-7_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-7_openblas
  libcurl            conda-forge/linux-64::libcurl-7.71.1-hcdd3856_8
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_18
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-hff62375_18
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-hff62375_18
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_18
  libgpuarray        conda-forge/linux-64::libgpuarray-0.7.6-h14c3975_1003
  liblapack          conda-forge/linux-64::liblapack-3.9.0-7_openblas
  libnghttp2         conda-forge/linux-64::libnghttp2-1.41.0-h8cfc5f6_2
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_h4812303_1
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libprotobuf        conda-forge/linux-64::libprotobuf-3.14.0-h780b84a_0
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_5
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_18
  libtiff            conda-forge/linux-64::libtiff-4.2.0-hdc55705_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h36c2ea0_3
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_0
  mako               conda-forge/noarch::mako-1.1.4-pyh44b312d_0
  markdown           conda-forge/noarch::markdown-3.3.3-pyh9f0ad1d_0
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py37h5e8e339_3
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.3.3-py37h0c9df89_0
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  numpy              conda-forge/linux-64::numpy-1.19.5-py37haa41c4c_1
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openssl            conda-forge/linux-64::openssl-1.1.1i-h7f98852_0
  pandas             conda-forge/linux-64::pandas-1.2.0-py37hdc94413_1
  pillow             conda-forge/linux-64::pillow-8.1.0-py37he6b4880_1
  pip                conda-forge/noarch::pip-20.3.3-pyhd8ed1ab_0
  prodigal           bioconda/linux-64::prodigal-2.6.3-h516909a_2
  protobuf           conda-forge/linux-64::protobuf-3.14.0-py37hcd2ae1e_1
  pygpu              conda-forge/linux-64::pygpu-0.7.6-py37h902c9e0_1002
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  python             conda-forge/linux-64::python-3.7.9-hffdb5ce_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2020.5-pyhd8ed1ab_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py37h5e8e339_2
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  **scikit-learn       conda-forge/linux-64::scikit-learn-0.24.1-py37h69acf81_0**
  scipy              conda-forge/linux-64::scipy-1.6.0-py37h14a347d_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py37h89c1867_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.34.0-h74cdb3f_0
  tensorboard        conda-forge/linux-64::tensorboard-1.14.0-py37_0
  tensorflow         conda-forge/linux-64::tensorflow-1.14.0-h4531e10_0
  tensorflow-base    conda-forge/linux-64::tensorflow-base-1.14.0-py37h4531e10_0
  tensorflow-estima~ conda-forge/linux-64::tensorflow-estimator-1.14.0-py37h5ca1d4c_0
  termcolor          conda-forge/noarch::termcolor-1.1.0-py_2
  theano             conda-forge/linux-64::theano-1.0.3-py37hfc679d8_1
  threadpoolctl      conda-forge/noarch::threadpoolctl-2.1.0-pyh5ca1d4c_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  toolchain          pkgs/main/linux-64::toolchain-2.4.0-0
  toolchain_c_linux~ pkgs/main/linux-64::toolchain_c_linux-64-2.4.0-0
  toolchain_cxx_lin~ pkgs/main/linux-64::toolchain_cxx_linux-64-2.4.0-0
  tornado            conda-forge/linux-64::tornado-6.1-py37h5e8e339_1
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  werkzeug           conda-forge/noarch::werkzeug-1.0.1-pyh9f0ad1d_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  wrapt              conda-forge/linux-64::wrapt-1.12.1-py37h5e8e339_3
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  zipp               conda-forge/noarch::zipp-3.4.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010
  zstd               conda-forge/linux-64::zstd-1.4.8-ha95c52a_1

**The scikit-learn version is the latest (0.24.1) - was the model trained using this version or an older one?**

**Comment by prihoda** [comment]
Hi @aescasinas, thanks for the heads up! I fixed it in our setup.py and in bioconda, it should be up in a day or so.
