### ISSUE TITLE
How to use DeepBGC's results to the antiSMASH

### ISSUE THREAD

**Issue by yangziyi1990** [Merck/deepbgc#45]
I see that antiSMASH 6.0 has added a specification of a JSON based file format that allows users to load gene cluster predictions from DeepBGC to be displayed alongside antiSMASH's own results. When I run the DeepBGC, there are no *.json file generated. I used the following code:
$ deepbgc pipeline test/data/BGC0000015.fa --output work/BGC0000015
So, how can i obtain the *.json file?

And, another question, how to use the DeepBGC‘s result (*.json file) to the antiSMASH?
Looking forward for your reply, Thank you very much!

**Comment by prihoda** [comment]
Hi @yangziyi1990, thanks for the heads up! I didn't notice antiSMASH 6 is already available. We were actually working on the JSON output earlier, so we are ready. 

I enabled the JSON output and released a new DeepBGC version (0.1.23), it will be available on Bioconda within a day or so, then you can `conda install deepbgc==0.1.23`. 

The JSON file is created in the output folder, you can upload it to antiSMASH:

![image](https://user-images.githubusercontent.com/2894124/108829537-97770200-75c8-11eb-87e1-12b65a6e381b.png)

**Comment by yangziyi1990** [comment]
Thank you very much! But I still have some problem that need you help.

**Comment by yangziyi1990** [comment]
Thank you very much! But I still have some problem that need you help.

**Comment by yangziyi1990** [comment]
Thank you very much! But I still have some problem that need you help. Does the deepBGC 0.1.23 release on the github? The other one is how to upload the json file to antiSMASH，I can't find the upload location. Thank you very much!

**Comment by yangziyi1990** [comment]
![1614075847452](https://user-images.githubusercontent.com/20346636/108831319-eb074100-7604-11eb-9381-e1c1025637f2.jpg)

**Comment by prihoda** [comment]
The release is now on GitHub and on pypi, you can install using pip already: `pip install deepbgc==0.1.23`. The bioconda release for installing through conda will be available tomorrow. 

The JSON file needs to be uploaded when submitting your antiSMASH job, by selecting "Upload extra annotations" on https://antismash.secondarymetabolites.org/

**Comment by yangziyi1990** [comment]
![image](https://user-images.githubusercontent.com/20346636/108832857-07a47880-7607-11eb-84cb-f3818d37f2a7.png)
Hi, prihoda, the latest version of DeepBGC seems not work~

**Comment by prihoda** [comment]
Hmm, it works for me, I guess you can try again later. In any case, the conda version should be available tomorrow.

**Comment by yangziyi1990** [comment]
![image](https://user-images.githubusercontent.com/20346636/108833026-3c183480-7607-11eb-838d-ccf1d6d441ed.png)
In the website of antiSMASH，I can't find out the button about "Upload extra annotations"……

**Comment by yangziyi1990** [comment]
> Hmm, it works for me, I guess you can try again later. In any case, the conda version should be available tomorrow.

Ok, I will try it later, thank you very much!

**Comment by prihoda** [comment]
That's strange, here's what I see:

![image](https://user-images.githubusercontent.com/2894124/108833496-3271db00-75cd-11eb-9703-3c4da2f8e127.png)

You can try refreshing the page, or removing cache... Or contacting the antiSMASH support.

**Comment by yangziyi1990** [comment]
Now, I changed the browser and it appeared! Thank you very much!

**Comment by yangziyi1990** [comment]
prihoda, I download the deepBGC from github just now. And I install is on my computer by using "python setup.py build & install". The data in the test file that i test, but the output does not have the json file. Did I do something wrong?
![image](https://user-images.githubusercontent.com/20346636/108835990-3fadba80-760b-11eb-9b9f-0b2fd3d03db8.png)

**Comment by prihoda** [comment]
You can try running `pip install .` inside the directory to install again, what output do you get for that?

**Comment by yangziyi1990** [comment]
Yes，It works. And I upload the json file to the website of antiSMASH to test it. Thanks for your patience to help me solve the problem!

**Comment by prihoda** [comment]
Great, I'll close this issue now, let me know if you have any more questions.
