### ISSUE TITLE
gbff GenBank file format is not recognised

### ISSUE THREAD

**Issue by gkapatai** [Merck/deepbgc#57]
Can you please add gbff in EXTENSIONS_GENBANK? The format is compatible as just renaming the file to gbk allows the run to complete successfully.

**Comment by prihoda** [comment]
Hi @gkapatai, sure, can you create a pull request yourself? You can edit the file directly on GitHub, it will create your personal fork of this repository and let you submit a pull request with the change

**Comment by prihoda** [comment]
Thanks for that pull request @gkapatai, the new version 0.1.27 is now on pypi, you can install using `pip install deepbgc==0.1.27`. It should also appear on bioconda in a few days.
