### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by NiklausChung** [Merck/deepbgc#75]
Hi, there!
I've downloaded 'DeepBGC' on my Mac successfully, but there's some issue reported as follows when I tapped in 'deepbgc info'.
`=================|_|===== version 0.1.30 =====
INFO    26/06 22:03:07   Available data files: ['Pfam-A.31.0.hmm.h3f', 'Pfam-A.31.0.hmm.h3i', 'Pfam-A.31.0.clans.tsv', 'Pfam-A.31.0.hmm', 'Pfam-A.31.0.hmm.h3p', 'Pfam-A.31.0.hmm.h3m']
INFO    26/06 22:03:07   ================================================================================
INFO    26/06 22:03:07   Available detectors: ['clusterfinder_retrained', 'clusterfinder_geneborder', 'clusterfinder_original', 'deepbgc']
INFO    26/06 22:03:07   --------------------------------------------------------------------------------
INFO    26/06 22:03:07   Model: clusterfinder_retrained
INFO    26/06 22:03:07   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/detector/clusterfinder_retrained.pkl
WARNING 26/06 22:03:07   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    26/06 22:03:07   --------------------------------------------------------------------------------
INFO    26/06 22:03:07   Model: clusterfinder_geneborder
INFO    26/06 22:03:07   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/detector/clusterfinder_geneborder.pkl
WARNING 26/06 22:03:07   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    26/06 22:03:07   --------------------------------------------------------------------------------
INFO    26/06 22:03:07   Model: clusterfinder_original
INFO    26/06 22:03:07   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/detector/clusterfinder_original.pkl
WARNING 26/06 22:03:07   Model not supported: ('Package "hmmlearn" needs to be installed to run ClusterFinder HMM. ', 'Install extra dependencies using: \n    pip install "deepbgc[hmm]"')
INFO    26/06 22:03:07   --------------------------------------------------------------------------------
INFO    26/06 22:03:07   Model: deepbgc
INFO    26/06 22:03:07   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/detector/deepbgc.pkl
Using TensorFlow backend.
WARNING 26/06 22:03:08   Model not supported: ("Error unpickling model from path '/Users/Work/Library/Application Support/deepbgc/data/0.1.0/detector/deepbgc.pkl'", TypeError('Descriptors cannot not be created directly.\nIf this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\nIf you cannot immediately regenerate your protos, some other possible workarounds are:\n 1. Downgrade the protobuf package to 3.20.x or lower.\n 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n\nMore information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates'))
INFO    26/06 22:03:08   ================================================================================
INFO    26/06 22:03:08   Available classifiers: ['product_activity', 'product_class']
INFO    26/06 22:03:08   --------------------------------------------------------------------------------
INFO    26/06 22:03:08   Model: product_activity
INFO    26/06 22:03:08   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/classifier/product_activity.pkl
/Users/Work/opt/miniconda3/envs/deepbgc/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/Work/opt/miniconda3/envs/deepbgc/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
INFO    26/06 22:03:08   Type: RandomForestClassifier
INFO    26/06 22:03:08   Version: 0.1.0
INFO    26/06 22:03:08   Timestamp: 1551781433.886473 (2019-03-05T18:23:53.886473)
INFO    26/06 22:03:08   --------------------------------------------------------------------------------
INFO    26/06 22:03:08   Model: product_class
INFO    26/06 22:03:08   Loading model from: /Users/Work/Library/Application Support/deepbgc/data/0.1.0/classifier/product_class.pkl
INFO    26/06 22:03:08   Type: RandomForestClassifier
INFO    26/06 22:03:08   Version: 0.1.0
INFO    26/06 22:03:08   Timestamp: 1551781410.019103 (2019-03-05T18:23:30.019103)
INFO    26/06 22:03:08   ================================================================================
WARNING 26/06 22:03:08   Some warnings detected, check the output above
`
It looks like something is blocking me from accessing the file 'deepbgc.pkl', or maybe something is incompatible with 'deepbgc.pkl'. I tried to run the script as stated in 'README', using a partial sequence from my genome. It seems the question stands that 'deepbgc.pkl' is not working as supposed (see the picture).
![error](https://user-images.githubusercontent.com/93632072/175820241-3dec8f7a-093d-45f5-8c64-8b7efec36472.png)
)

**Comment by NiklausChung** [comment]
Hi@prihoda thanks for your help. After reinstalling deepbgc as you recommended, now deepbgc is fully functional on my mac. 
However, the whole 'sideload json file to AntiSMASH' thing still bothers me. In short, deepbgc predicted that there's over 300 BGCs in the genome of interest (see the quote), which is pretty impressive given the rare nature of the species; but when I uploaded the genome file and the extra annotation (aka. deepbgc's json file, see the picture), the result was reduced to only 18 BGCs (see the picture). Considering that without the extra json file provided to the AntiSMASH, the result was no different. I was wondering that if I used the json file correctly, and if you could help me understand how the result can be sideload to antiSMASH.

> ================================================================================
Detected 306 total BGCs using deepbgc model
Number of BGCs with predicted product_class: 
 no confident class: 199
 Polyketide: 69
 Terpene: 30
 RiPP: 12
 NRP: 9
 Saccharide: 2
 Other: 1
Number of BGCs with predicted product_activity: 
 antibacterial: 216
 no confident class: 80
 antifungal: 18
 inhibitor: 10
========================================
Saved DeepBGC result to: Assembled_Genome
========================================
<img width="1435" alt="截屏2022-07-03 下午11 45 52" src="https://user-images.githubusercontent.com/93632072/177047170-716b2f0f-b299-4b09-9558-6c4715f01f58.png">
<img width="1550" alt="截屏2022-07-03 下午11 46 23" src="https://user-images.githubusercontent.com/93632072/177047245-49b3d01d-dd18-4ef8-ab88-1c089ade0683.png">

**Comment by ne1al** [comment]
@prihoda I actually installed DeepBGC today as guided by creating a new conda environment and followed each step, however, when I tried `deepbgc pipeline contig.fasta`, I encountered an error due to `protobuf` package as attached in screenshot. Would you please advise?
<img width="1440" alt="Screen Shot 2022-07-19 at 7 38 54 PM" src="https://user-images.githubusercontent.com/48625859/179814492-8c30e510-adad-48c0-b774-166fc1135a8f.png">
e

**Comment by NiklausChung** [comment]
> @prihoda I actually installed DeepBGC today as guided by creating a new conda environment and followed each step, however, when I tried `deepbgc pipeline contig.fasta`, I encountered an error due to `protobuf` package as attached in screenshot. Would you please advise?
> <img alt="Screen Shot 2022-07-19 at 7 38 54 PM" width="1440" src="https://user-images.githubusercontent.com/48625859/179814492-8c30e510-adad-48c0-b774-166fc1135a8f.png">
> e

I think you should try to downgrade the buffer to 3.19.0 (worked for me). Just do as the last lines in screenshot recommended.

**Comment by prihoda** [comment]
Should now be fixed in new deepbgc version on bioconda
