### ISSUE TITLE
run Deepbgc in fungal genomes

### ISSUE THREAD

**Issue by Juliana-Soto24** [Merck/deepbgc#81]
I see that Deepbgc uses prodigal for gene prediction. Is there a way to run Deepbgc for fungal genomes using another gene prediction tool? 

Thanks, 
Juliana

**Comment by prihoda** [comment]
Hi @Juliana-Soto24 DeepBGC supports GenBank input, so if there are any CDS feature annotations already present, it will use them instead of running prodigal.
