### ISSUE TITLE
Use https instead of ftp protocol for Pfam database download

### ISSUE THREAD

**Issue by jasmezz** [Merck/deepbgc#93]
Since the Pfam FTP links have been discontinued, would you update the respective `deepbgc/data.py` script that downloads the Pfam databases?

I would create a pull request myself but saw that a [branch](https://github.com/Merck/deepbgc/tree/prihoda-patch-2) from last month already exists in this repo that fixes it.

So the sooner you release an updated version, the happier I would be since deepbgc is part of a [gene function screening pipeline](https://github.com/nf-core/funcscan) that colleagues and I develop.

**Comment by prihoda** [comment]
Merged and released to pypi, please update using: `pip install deepbgc==0.1.31`
